---
preset: conventionalcommits
tagFormat: 'v${version}'

branches: main
  
plugins:
  - '@semantic-release/npm'
  - '@semantic-release/git'
  - '@semantic-release/github'

verifyConditions:
  - '@semantic-release/npm'
  - '@semantic-release/git'
  - '@semantic-release/github'

analyzeCommits:
  - path: '@semantic-release/commit-analyzer'

generateNotes:
  - path: '@semantic-release/release-notes-generator'

prepare:
  - path: '@semantic-release/changelog'
    changelogFile: 'CHANGELOG.md'
  - path: '@semantic-release/npm'
  - path: '@semantic-release/git'

publish:
  - path: '@semantic-release/github'

success:
  - '@semantic-release/github'
